name: Feature Template
description: 기능 추가
title: "[Feature]: 제목을 작성해주세요"
labels: ["feature"]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: 어떤 기능인가요?
      description: 추가하려는 기능에 대해 간결하게 설명해주세요.
      placeholder: ex. 타이머 화면 그리기
    validations:
      required: true

  - type: textarea
    id: feature-details
    attributes:
      label: 작업 상세 내용
      description: 어떤 작업을 할 것인지 TODO 목록을 작성해주세요.
      value: |
        - [ ] TODO 1
        - [ ] TODO 2
        - [ ] TODO 3
    validations:
      required: true

  - type: textarea
    id: reference-materials
    attributes:
      label: 참고할만한 자료(선택)
      description: 관련 링크, 레퍼런스 등 (선택 사항)
      placeholder: ex. https://example.com/docs/...
    validations:
      required: false
